yarnPath: .yarn/releases/yarn-2.4.2.cjs

plugins:
  - path: .yarn/plugins/@yarnpkg/plugin-version.cjs
    spec: "@yarnpkg/plugin-version"

packageExtensions:

  # problem (https://github.com/webpack/webpack-dev-server/issues/2807):
  # webpack-dev-middleware@3.x is not compatible with webpack 5
  #   but webpack-dev-middleware@4.x (already officially released) IS compatible.
  # when webpack-dev-server@4.x is out of beta and supports webpack-dev-middleware@4.x,
  #   update the example-projects/(react|vue)* packages (and others?)
  # when webpack-dev-server@4.x is out of beta and @angular-devkit/build-angula supports it,
  #   update packages-contrib/angular and example-projects/angular
  webpack-dev-server@~3.11.0:
    dependencies:
      webpack-dev-middleware: ^4.0.0

  # https://github.com/vuejs/vue-test-utils-next/issues/245
  "@vue/test-utils@2.*":
    dependencies:
      "@vue/compiler-dom": "*"

  # TODO: file an issue for this
  "@nuxt/components@2.*":
    dependencies:
      "consola": "*"

  # lazy libs that don't define jquery as a dependency
  "components-jqueryui@*":
    dependencies:
      "jquery": "*"
  "jquery-simulate@*":
    dependencies:
      "jquery": "*"
  "jasmine-jquery@*":
    dependencies:
      "jquery": "*"

# # for verdaccio testing
# # first, run `yarn npm login` with made-up credentials
# npmRegistryServer: http://localhost:4873/
# unsafeHttpWhitelist:
#   - localhost
